[MeasureCPUCore0]
Measure=Plugin
Plugin=CoreTemp
CoreTempType=Load
CoreTempIndex=0
MaxValue=100
UpdateDivider=3

[MeasureCPUCore1]
Measure=Plugin
Plugin=CoreTemp
CoreTempType=Load
CoreTempIndex=1
MaxValue=100
UpdateDivider=3

[MeasureCPUCore2]
Measure=Plugin
Plugin=CoreTemp
CoreTempType=Load
CoreTempIndex=2
MaxValue=100
UpdateDivider=3

[MeasureCPUCore3]
Measure=Plugin
Plugin=CoreTemp
CoreTempType=Load
CoreTempIndex=3
MaxValue=100
UpdateDivider=3

; [MeasureCPUCore1]
; Measure=CPU
; Processor=1

; [MeasureCPUCore2]
; Measure=CPU
; Processor=2

; [MeasureCPUCore3]
; Measure=CPU
; Processor=3

; [MeasureCPUCore4]
; Measure=CPU
; Processor=4
