[Variables]

; Path to style folder
StylePath=#@#Styles\Default\

; Index of WiFi adapter to use - 0 should usually be fine, if issues arise try 1, 2, etc
WiFiAdapterID=0

; Drive letter for disk drives
Drive1=C:
Drive2=E:

; "Best" autodetects the active interface; change to 0 to measure all interfaces, etc
NetInterface=Best

; ENSURE THESE VALUES ARE CORRECTLY SET
; Download speed in Mbps
NetDownstreamSpeed=16
; Upload speed in Mbps
NetUpstreamSpeed=1.28

; Tweak this until the visualizer range about matches the system output levels
VisualizerGain=5.0
