[MeterBand0]
Meter=Bar
MeasureName=MeasureBand0
MeterStyle=MeterStyleVisualizerBar
X=4
Y=5

[MeterBand1]
Meter=Bar
MeterStyle=MeterStyleVisualizerBar
MeasureName=MeasureBand1

[MeterBand2]
Meter=Bar
MeterStyle=MeterStyleVisualizerBar
MeasureName=MeasureBand2

[MeterBand3]
Meter=Bar
MeterStyle=MeterStyleVisualizerBar
MeasureName=MeasureBand3

[MeterBand4]
Meter=Bar
MeterStyle=MeterStyleVisualizerBar
MeasureName=MeasureBand4

[MeterBand5]
Meter=Bar
MeterStyle=MeterStyleVisualizerBar
MeasureName=MeasureBand5

[MeterBand6]
Meter=Bar
MeterStyle=MeterStyleVisualizerBar
MeasureName=MeasureBand6

[MeterBand7]
Meter=Bar
MeterStyle=MeterStyleVisualizerBar
MeasureName=MeasureBand7

[MeterBand8]
Meter=Bar
MeterStyle=MeterStyleVisualizerBar
MeasureName=MeasureBand8

[MeterBand9]
Meter=Bar
MeterStyle=MeterStyleVisualizerBar
MeasureName=MeasureBand9
